# Generated by Django 5.1.1 on 2024-09-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField()),
                ('Title', models.TextField()),
                ('Teacher_name', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('Piority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('Complete', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.TextField()),
                ('Password', models.TextField()),
                ('Phone_number', models.TextField()),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Type_of_profile', models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher')], max_length=20)),
                ('About', models.TextField(blank=True, null=True)),
                ('Login', models.BooleanField(null=True)),
            ],
        ),
    ]
